# site settings
title: Personal Website
subtitle: Pedro Martins

call_to_action: "Get to know me"
description: I'm a robotics and computer vision enthusiastic! </br> And love to plan events and workshops

baseurl: "/" # the subpath of your site, e.g. /blog

url: https://martinspedro.github.io/portfolio-website # the base hostname & protocol for your site
author: Pedro Martins

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets/Pedro-Martins-CV.pdf

# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555
# email: youremailaddress@gmail.com

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
# 500px_url:
# facebook_url:
github_url: https://www.github.com/martinspedro
# gitlab_url:
# googleplus_url:
# instagram_url:
linkedin_url: https://www.linkedin.com/in/pedro-martins
# pinterest_url:
# slack_url:
# twitter_url:

# build settings
markdown: kramdown
include: [_pages]
sass:
  style: compressed
